// The scene's mood: its light, air and glow, as Adrian tuned them.
export const MOOD = {
  exposure: 0.65,
  ambient: 0.5,
  hemisphere: 0.8,
  spot: 30,
  lamp: 25,
  p03Light: 6.5,
  deckLight: 14,
  handLight: 3,
  rackLight: 7.5,
  // How far the white lamps lean to the palette's own colour.
  lampTint: 0.7,
  fogNear: 6.5,
  fogFar: 34,
  bloom: 1.4,
  // Only what is brighter than white glows, so the lamps never make a card glow.
  bloomThreshold: 1,
  bloomRadius: 0.45,
  vignette: 0.75,
  noise: 0.05,
  scanline: 0.05,
  hue: 0,
  saturation: 0,
  brightness: 0,
  contrast: 0,
  dustCount: 320,
  dustSize: 2.8,
  dustOpacity: 0.2,
  dustSpeed: 0.2,
  cardGlow: 0.65,
  cardBloom: 0.5,
  trimGlow: 0.04,
} as const
